### PR TITLE
Fix broken yml for GitHub Actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
It seems to now be failing due to a failing rebar3 version (the one packed with the Docker container).

**Comment by paulo-ferraz-oliveira** [comment]
Converting to draft to check if Action `setup-erlang` would solve the (apparently caused by) `rebar3` issues.

**Comment by paulo-ferraz-oliveira** [comment]
I'm trying to [make CI's `rebar3` not change](https://github.com/erlang/docker-erlang-otp/pull/317) between different containers. While this isn't done, I'm going to use `setup-erlang` for a quick fix.

**Comment by paulo-ferraz-oliveira** [comment]
List of Erlang versions is currently: 19.3, 20.0, 21.3, 22.3, 23.1
List of `setup-erlang` supported version is currently: http://packages.erlang-solutions.com/erlang/debian/pool/.

I'll need to fix the mismatch.

**Comment by paulo-ferraz-oliveira** [comment]
Still not Okay :( it seems `setup-erlang` prefixes the version with `https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_erlang:` and suffixes it with `-1~ubuntu~bionic_amd64.deb`, so I need to work with that.

**Comment by elbrujohalcon** [comment]
Looks reasonable to me.

**Pull request merged**
