### PR TITLE
Fix unwarranted match as found by OTP 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
As introduced by https://github.com/erlang/otp/pull/2995. Fun times!

(also, I wrote the original code, and it would be strange for me to not have done that "match" in error)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
A release of this inside `rebar3_lint` would be nice. Shall I? (I'm not actually sure about the whole routine you apply before a release).

**Comment by elbrujohalcon** [comment]
Awesome findings!! Thanks, @richcarl :)

**Comment by elbrujohalcon** [comment]
> A release of this inside `rebar3_lint` would be nice. Shall I? (I'm not actually sure about the whole routine you apply before a release).

We first need a release of `elvis_core`… Then you can send a PR against `rebar3_lint` and then… you're an admin there… you can release it at your own will.

**Comment by elbrujohalcon** [comment]
https://hex.pm/packages/elvis_core/1.1.1

**Comment by paulo-ferraz-oliveira** [comment]
Thanks.

Also, yeah, this new warning is nice.

**Pull request merged**
