### PR TITLE
Complete removal of `seqbind` references

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I didn't think about looking for `seqbind` in the code base, at the time

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]

**Comment by elbrujohalcon** [comment]
You need to update rebar.lock as well

**Comment by paulo-ferraz-oliveira** [comment]
`seqbind` isn't there, but I can push an updated (as in `rebar 3.14.1`) file, nonetheless.

**Comment by elbrujohalcon** [comment]
Oh, right… it was a test dep… 🤦 
It's fine to push a new rebar.lock, yes… but you also need to appease Travis.

**Comment by paulo-ferraz-oliveira** [comment]
> Oh, right… it was a test dep… 🤦
> It's fine to push a new rebar.lock, yes… but you also need to appease Travis.

I'll look into why the tests are failing, since locally they're not (using the `Makefile` procedure`).

**Comment by elbrujohalcon** [comment]
As a matter of fact, if you could simplify Travis integration to be something more akin to [this](https://github.com/AdRoll/spillway/blob/master/.travis.yml) (without the formatting), that would be lovely. We had too many hacks in our Travis integration back then because the support for Erlang was limited.

**Comment by paulo-ferraz-oliveira** [comment]
What `email` would you use? Or shouldn't that option exist?

**Comment by elbrujohalcon** [comment]
Remove that part.

**Comment by paulo-ferraz-oliveira** [comment]
Should we also remove the `rebar3` executable (found at the root)?

**Comment by elbrujohalcon** [comment]
Yes, remove that one, too.

**Review by elbrujohalcon — APPROVED** [review]

**Pull request merged**
