### PR TITLE
Act on `non_reversible_form` as an exception to atom naming conventions

### LINKED ISSUE #344: Problem with atom on line -1 related to maybe ... end clause
## Bug Description

During ```rebar3 lint``` I got a warning on line -1 which is related to the ```maybe ... end``` clause

## To Reproduce

```erlang
-module(test_maybe).

-feature(maybe_expr, enable).

-export([sum_numbers/2]).


sum_numbers(Number1, Number2) ->
    maybe
        ValidNumber1 ?= validate_number(Number1),
        ValidNumber2 ?= validate_number(Number2),
        Result = ValidNumber1 + ValidNumber2,
        io:format("Results: ~p~n", [Result])
    else
        {error, invalid_number} ->
            {error, "One or both inputs are invalid numbers"}
    end.

validate_number(Number) when is_number(Number) ->
    Number;
validate_number(_) ->
    {error, invalid_number}.
```

## Expected Behavior

no warning on line -1

## `rebar3` Logs

```erlang
===> elvis analysis starting, this may take a while...
# src/test_maybe.erl [FAIL]
  - atom_naming_convention (https://github.com/inaka/elvis_core/tree/main/doc_rules/elvis_style/atom_naming_convention.md)
    - Atom [] on line -1 does not respect the format defined by the regular expression '"^[a-z]([a-z0-9@]*_?)*(_SUITE)?$"'.
===> Linting failed
```

## Additional Context

- OS: WSL2
- Erlang version: Erlang/OTP 26
- rebar3 version: rebar 3.23.0

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #344.

@elbrujohalcon, not really sure we should make this more explicit with a test (?)

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]
A test would be nice, but we can merge the PR as-is if you like, too.

**Comment by paulo-ferraz-oliveira** [comment]
I'll update the existing test with a simple thing.

**Comment by paulo-ferraz-oliveira** [comment]
If the test passes I'm merging with your approval.

**Comment by paulo-ferraz-oliveira** [comment]
GitHub 3.2.4: https://github.com/inaka/elvis_core/releases/tag/3.2.4
Hex 3.2.4: https://hex.pm/packages/elvis_core/3.2.4

**Pull request merged**
