### PR TITLE
Move docs from wiki to code

### LINKED ISSUE #252: Move docs from wiki to code
## Is your feature request related to a problem? Please describe.
Wikis are apart from code so each pull request for a new or updated rule (which are most of the PRs, anyway) requires an extra update somewhere else.
It would be better if what's now on the wiki would be in the README or in a `doc` folder (maybe with one md document per rule?).

## Describe the solution you'd like
I would like to move the current documentation from the wiki to somewhere in the code.

## Describe alternatives you've considered
None.

## Additional Context
As a bonus: I would like that to be uploaded to hexdocs when the project is published.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #252 and touches https://github.com/inaka/elvis_core/issues/167#issuecomment-702371801.

After this we can probably hide the Wiki from the project.

### CODE REVIEW

**Review by elbrujohalcon — APPROVED** [review]
I like it as it is, but I was wondering if it would made our life easier in the future to have per-module subfolders, like `elvis_style/dont_repeat_yourself.md` instead of just `dont_repeat_yourself.md` 🤔

**Comment by paulo-ferraz-oliveira** [comment]
I can do that, no prob. I believe the module name should be in the context of the execution, already.

**Comment by elbrujohalcon** [comment]
Yeah… and… in _theory_ we can totally have `elvis_style:no_tabs` and `elvis_project:no_tabs`. I can't think of any good reason to do that… but, it's in fact possible.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, the module is out of context, but it doesn't seem hard to get. I'll try to do this at lunch, today.

**Pull request merged**
