### PR TITLE
support ignore option in nesting_level and dont_repeat_yourself

### PR DESCRIPTION
**Pull request by stolen**
With this patch user can ignore some modules in `nesting_level` and `dont_repeat_yourself` rules.

### CODE REVIEW

**Comment by stolen** [comment]
Also ignore code is copy-pasted a lot. Maybe there is better place for it?

**Comment by elbrujohalcon** [comment]
@stolen would you mind adding some tests for this?

**Comment by elbrujohalcon** [comment]
and if you manage to refactor the code in order to avoid all that copy/pasting… that would be awesome!

**Comment by stolen** [comment]
OK, I'll try to refactor it when I have time.

**Pull request closed without merging**
