### PR TITLE
Make sure gen_statem follows the same rule as gen_server

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
Travis is not happy, @paulo-ferraz-oliveira :P

**Comment by paulo-ferraz-oliveira** [comment]
> Travis is not happy, @paulo-ferraz-oliveira :P

Let me check what it's complaining about. Tests pass locally, at least.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... I seem to have called `handle_event` `handle_call`. Tests don't fail, though, locally, so there's something I'm missing here.

**Comment by paulo-ferraz-oliveira** [comment]
A bit outside the scope of this, I took the liberty to update Travis CI instructions, to deal with more Erlang/OTP versions.

**Comment by paulo-ferraz-oliveira** [comment]
I'm now running the same as Travis CI runs (I added a Makefile and a `ct` target to it) and can see the issues show up. This is better than having to wait for GitHub to tell me where I got stuff wrong.

**Comment by paulo-ferraz-oliveira** [comment]
> Travis is not happy, @paulo-ferraz-oliveira :P

Travis is no longer angry at me.

**Review by elbrujohalcon — APPROVED** [review]
This PR is fine, but I would like to eventually simplify our travis integration, to something like [this](https://github.com/AdRoll/spillway/blob/master/.travis.yml) since there is support for rebar3 on Travis now.

**Pull request merged**
