### PR TITLE
elvis.config options for application:get_env/2,3

### LINKED ISSUE #197: Fetch more options from elvis.config + rebar.config
At the moment, `elvis_core` depends on `application:get_env` which is not very usable for the consumer, especially if his/her project is not bound to a release.

The purpose of this task is to, while keeping backward compatibility, fetch further options from `elvis.config` + `rebar.config` for usability.

**Note**: search the code for `application:`.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #197.

~Opening as draft so we can discuss further.~

I committed in three different moments so the refactoring is easier to follow. Can squash before merge...

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
Looks good so far…

**Comment by paulo-ferraz-oliveira** [comment]
Moving away from draft. Whatever happens now is "needs a fix".

**Review by elbrujohalcon — CHANGES_REQUESTED** [review]
We just need to add a small note to the configuration section of the README stating which options can be set on the application environment. Other than that, I would merge this.

**Comment by paulo-ferraz-oliveira** [comment]
I've pushed that update. I'm gonna do a new pull request to brush up the README (it needs some ❤️).

**Pull request merged**
