### PR TITLE
New ruleset: `erl_files_strict`

### LINKED ISSUE #321: Have a simple way to run `all` checks (even optional ones)
## Is your feature request related to a problem? Please describe

I'm always frustrated when I have to study a static analysis tool to understand all its possibilities (and I don't think we're listing what rules we run by default 😢).

## Describe the solution you'd like

Something like an atom `all` in `elvis.config` to indicate "run all rules". This would then be overwritten by the specific rules that are configured in that same file.

## Describe alternatives you've considered

Reading through `elvis_core` and figuring out (as releases come out) which rules are "by default" and which ones aren't.

## Additional Context

N/A.

### PR DESCRIPTION
**Pull request by kivra-pauoli**
The goal of this ruleset, as discussed in #321, is to have all rules executing.

The first commit is just preparing the code for the feature.
The second commit is the feature implementation.

I implemented the tests in the simplest way possible, but it might hacky enough to warrant a comment to write them "better".

Closes #321.

### CODE REVIEW

**Comment by kivra-pauoli** [comment]
@elbrujohalcon, I can't seem to add you as a reviewer, so ping'ing you this way.

**Comment by elbrujohalcon** [comment]
That's because you're @kivra-pauoli and not @paulo-ferraz-oliveira , Mr. Split-Personality-Dude 🤪

**Comment by kivra-pauoli** [comment]
That much I know, but I thought anybody could add anybody as reviewers.

**Review by elbrujohalcon — APPROVED** [review]
I'm not sure if we have tests for these things, but this PR certainly has none :)

**Comment by elbrujohalcon** [comment]
> That much I know, but I thought anybody could add anybody as reviewers.

Nope. Only owners, admins, etc…

**Review by elbrujohalcon — APPROVED** [review]
Oh, I missed it! Sorry. 🤦🏻

**Comment by elbrujohalcon** [comment]
Feel free to generate a release with your other user if you think this is worth it, @kivra-pauoli :)

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I hope to release soon. Not a big change, but one we could benefit from right away. It'll also potentially imply a release next to `rebar3_lint`.

**Comment by paulo-ferraz-oliveira** [comment]
3.2.0 is released [on GitHub](https://github.com/inaka/elvis_core/releases/tag/3.2.0).
3.2.0 is released [on Hex](https://hex.pm/packages/elvis_core/3.2.0).

**Pull request merged**
